module.exports = {
    preset: "ts-jest",
    testEnvironment: "node",
    moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/src/$1'
    },
    collectCoverage: true,
    collectCoverageFrom: [
        "src/**/*.ts",
        "!src/index.ts",
        "!src/examples/**",
        "!src/commands/tspl/**",
        "!src/commands/index.ts",
        "!src/helpers/Image*.ts",
        "!src/helpers/ImageDataParser.ts",
        "!src/helpers/ImageProcessor.ts",
        "!src/helpers/ImageUtils.ts",
        "!src/helpers/Device.ts",
        "!src/helpers/NetworkDevice.ts",
        "!src/helpers/BonjourUtils.ts",
        "!src/helpers/USBUtils.ts",
        "!src/helpers/UnitUtils.ts",
        "!src/labels/index.ts",
        "!src/labels/fields/QRCode.ts",
        "!src/labels/fields/Text.ts",
        "!src/labels/fields/Table.ts",
        "!src/labels/Printable.ts",
        "!src/printers/Printer.ts",
        "!src/printers/PrinterService.ts",
        "!src/printers/index.ts",
        "!src/**/*.d.ts",
    ],
    coveragePathIgnorePatterns: [
        "/node_modules/",
        "/dist/",
        "/src/index.ts",
        "/src/examples/",
        "/src/commands/tspl/",
        "/src/commands/index.ts",
        "/src/helpers/Image",
        "/src/helpers/ImageDataParser.ts",
        "/src/helpers/ImageProcessor.ts",
        "/src/helpers/ImageUtils.ts",
        "/src/helpers/Device.ts",
        "/src/helpers/NetworkDevice.ts",
        "/src/helpers/BonjourUtils.ts",
        "/src/helpers/USBUtils.ts",
        "/src/helpers/UnitUtils.ts",
        "/src/labels/index.ts",
        "/src/labels/fields/QRCode.ts",
        "/src/labels/fields/Text.ts",
        "/src/labels/fields/Table.ts",
        "/src/labels/Printable.ts",
        "/src/printers/Printer.ts",
        "/src/printers/PrinterService.ts",
        "/src/printers/index.ts",
    ],
    coverageThreshold: {
        global: {
            branches: 75,
            functions: 75,
            lines: 75,
            statements: 75,
        }
    }
};